# NumPy

For commenting multiple lines - select lines and press Ctrl + /
In Jupyter Notebooks: 
1. Single hashtags(#) is used for Title
2. Double hashtags(##) is used for Topics
3. Triple hashtags(###) is used for sub-topics

## Multidimensiional Array

In [1]:
import numpy as np

In [2]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']]])
print(array.shape)

(3, 3, 3)


.shape() is to find the dimensions of the array

## Multidimensional Indexing

In [4]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', '_']]])
print(array[1, 1, 1])

N


In [5]:
word1 = array[0, 0, 0] + array[2,0,0] + array[2,0,0]
print(word1)

ASS


In [6]:
word2 = array[0,1,0] + array[0,1,1] + array[2,1,0] + array[0,0,0] + array[2,0,0] + array[0,2,1] + array[1,2,2] + array[0,1,1]*2
print(word2)

DEVASHREE


## Slicing

In [12]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

array[start : end : step]

In [13]:
print(array[0:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[0:] this tells python to select everything till the end

In [14]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


this will tell python to give everything, except 2nd row

In [15]:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


this will return all the rows reversed because step is -1

In [16]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


this will tell python to give everything on 2nd row

In [17]:
print(array[0,0])

1


 first is the row and second is the column

In [18]:
print(array[:,0])

[ 1  5  9 13]


this will print all the elements from the column index 0

In [19]:
print(array[:,-1])

[ 4  8 12 16]


-1 index is used when we don't know the last index

In [20]:
print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


this will access first 3 columns

In [21]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


this reverses our arrays

In [22]:
print(array[0:2, 2:])

[[3 4]
 [7 8]]


## Arithmetic

### 1. Scalar

In [23]:
array = np.array([1, 2, 3])

In [24]:
print(array +1)

[2 3 4]


In [25]:
print(array -2)

[-1  0  1]


In [26]:
print(array*3)

[3 6 9]


In [27]:
print(array / 4)

[0.25 0.5  0.75]


In [28]:
print(array**5)

[  1  32 243]


### 2. Vector

In [29]:
array = np.array([1, 2, 3])

In [30]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [31]:
array = np.array([1.01, 2.5, 3.99])

In [32]:
print(np.round(array)) 

[1. 2. 4.]


.round() is used to round off

In [33]:
print(np.floor(array))

[1. 2. 3.]


.floor() is used to round down

In [34]:
print(np.ceil(array))

[2. 3. 4.]


.ceil() is used to round up

In [35]:
print(np.pi)

3.141592653589793


In [36]:
radii = np.array([1, 2, 3])
print(np.pi*(radii**2))

[ 3.14159265 12.56637061 28.27433388]


## Comparison Operators

In [37]:
scores = np.array([91,55,100,73,82,64])

In [38]:
print(scores == 100)

[False False  True False False False]


In [39]:
print(scores <= 60)

[False  True False False False False]


In [41]:
print(scores >= 60)

[ True False  True  True  True  True]


In [43]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


## Broadcasting
Conditions: 
1. If the dimensions match 
2. If one of the dimensions has a size of one (for example: (4,1)&(1,4))


In [47]:
array1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
array2 = np.array([[1], [2], [3], [4]])

In [48]:
print(array1.shape)
print(array2.shape)

(4, 4)
(4, 1)


here both the conditions are satisfied 

In [49]:
array1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]])
array2 = np.array([[1,2], [2,3], [3,4], [4,5]])

In [50]:
print(array1.shape)
print(array2.shape)

(4, 4)
(4, 2)


In [51]:
print(array1*array2)

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

this gives an error since only 1 Dimensions match and the others don't

In [52]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

In [53]:
print(array1.shape)
print(array2.shape)
print(array1*array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## Agregate Functions

In [70]:
array = np.array([[1,2,3,4,5],
                    [6,7,8,9,10]])

In [71]:
print(np.sum(array))

55


In [72]:
print(array.mean())

5.5


In [73]:
print(array.std())

2.8722813232690143


In [74]:
print(array.var())

8.25


In [75]:
print(array.min())

1


In [76]:
print(array.max())

10


In [78]:
print(array.argmin())

0


In [79]:
print(array.argmax())

9


In [80]:
print(array.sum(axis =0))

[ 7  9 11 13 15]


axis = 0 is for column addition

In [81]:
print(array.sum(axis =1))

[15 40]


axis = 1 is for row addition

## Filtering

In [82]:
ages = np.array([[21,17,19,20,16,30,18,65],
                [39,22,15,99,18,19,20,21]])

In [84]:
teenagers = ages[ages < 18]
print(teenagers)

[17 16 15]


This flattens the 2D array 

Use where clause when u need to preserve the shape of your array

In [85]:
teenagers = np.where(ages < 18, ages, 0)
print(teenagers)

[[ 0 17  0  0 16  0  0  0]
 [ 0  0 15  0  0  0  0  0]]


In [86]:
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [87]:
seniors = ages[ages >= 65]
print(seniors)

[65 99]


In [88]:
evens = ages[ages % 2 == 0]
print(evens)

[20 16 30 18 22 18 20]


In [89]:
odds = ages[ages % 2 != 0]
print(odds)

[21 17 19 65 39 15 99 19 21]


## Random Numbers

In [90]:
rng = np.random.default_rng()
print(rng.integers(1,7))

1


In [93]:
rng = np.random.default_rng(seed = 1)
print(rng.integers(1,7))

3


seed is to get the previous output....basically everyone gets the same output

In [94]:
print(rng.integers(low=1, high=101, size=3))

[52 76 96]


this is to access 3 random numbers which will be stores in a 1D array

In [95]:
print(rng.integers(low=1, high=101, size=(3,2)))

[[ 4 15]
 [83 95]
 [25 32]]


this will create an array with 3 rows and 2 columns

In [97]:
np.random.seed(seed=1)
print(np.random.uniform(low=-1, high=1, size=(3,2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


### Shuffeling arrays

In [98]:
rng = np.random.default_rng()

In [99]:
array= np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[4 3 1 5 2]


.shuffle() - shuffles the elements in the array

In [100]:
fruits = np.array(["apple", "orange", "banana", "cocnut", "pineapple"])
fruit = rng.choice(fruits, size =(2,4))
print(fruit)

[['banana' 'orange' 'banana' 'apple']
 ['cocnut' 'orange' 'apple' 'pineapple']]


In [101]:
fruits = np.array(["🍎", "🍊", "🍌", "🥥", "🍍"]) # emojis : Window key + .(dot)
fruit = rng.choice(fruits, size =(2,4))
print(fruit)

[['🥥' '🍎' '🍎' '🍌']
 ['🍊' '🥥' '🍊' '🍍']]
